apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nasqar.fullname" . }}
  labels:
    {{- include "nasqar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nasqar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nasqar.selectorLabels" . | nindent 8 }}
    spec:
   {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nasqar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: efs-volume
              subPath: {{ (trimPrefix "/" .Values.efsProvisioner.path) }}
              mountPath: /efs
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: efs-volume
        nfs:
          {{- if .Values.efsProvisioner.dnsName }}
          server: {{ .Values.efsProvisioner.dnsName }}
          {{- else }}
          server: {{ .Values.efsProvisioner.efsFileSystemId }}.efs.{{ .Values.efsProvisioner.awsRegion }}.amazonaws.com
          {{- end }}
          path: /
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
